name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Or replace with the name of your default branch if it's not "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install sphinx
          pip install sphinx_rtd_theme
          pip install sphinxcontrib-napoleon  # For parsing NumPy-style docstrings

      - name: Build Documentation
        run: sphinx-build -b html docs docs/_build/html
        working-directory: .  # Ensures that the command is run from the repository root

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT2 }}
          publish_dir: docs/_build/html

